
name: My first Workflow

on:
  push:
  pull_request:   # ✅ add this

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello, Github Actions!"
      - name: Print name
        run: echo "Ravneet"

  say-bye:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello, Github Actions Bye!"
