name: My first Workflow

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: list file
        run: ls
        
  say-bye:
    needs: say-hello
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello, Github Actions Byee!"
 # By default jobs run parallely     
 # To run time in sequence, we use needs
 # RUNNERS:Runners are machine where jons run
 # Types of runners
 #1 Github-hosted-> e.g. windows,ubuntu
 #2 Self-hosted->e.g. your own server, your cloud virtual machine
 #Uses Action(keyword):
 # Actiosn: resulebale piece of code built in function provided by github
 # Steps: clone a repo
    
